project:
  type: book
  output-dir: docs

book:
  title: "CCIEA ESR Technical Documentation"
  subtitle: "California Current Integrated Ecosystem Assessment"
  author:
    - name: Greg Williams
      affiliation:
        - Northwest Fisheries Science Center
    - name: Lynn deWitt
      affiliation:
        - Southwest Fisheries Science Center
    - name: Isaac Schroeder
      affiliation:
        - Southwest Fisheries Science Center
    - name: Chris Dailey
      affiliation:
        - Northwest Fisheries Science Center
    - name: Nick Tolimieri
      affiliation:
        - Northwest Fisheries Science Center
  date: last-modified
  cover-image: "figures/BigSur2 1412030498-2641.jpg"
  favicon: "figures/favicon.ico"
  repo-url: https://github.com/CCIEA-esr/ESR-Technical-Documentation-FY2026/
  downloads: [pdf]
  navbar:
    background: "#276189"
    search: true
    logo: "figures/logo-5.png"
    logo-alt: "California Current Integrated Ecosystem Assessment Website"
    logo-href: "https://www.integratedecosystemassessment.noaa.gov/regions/california-current"
  sidebar: 
    search: false
    collapse-level: 1
  chapters:
    - index.qmd
    - part: Introduction
      chapters: 
        - Introduction.qmd
        - SamplingLocations.qmd
    - part: "General Methods"
      chapters:
      - DataCodeAccess.qmd
      - TimeSeriesQuadplots.qmd
      
    - part: "Climate and Oceans"
      chapters:
      - ONI.qmd
      - PDO.qmd
      - NPGO.qmd
      - NPH.qmd
      - SST.qmd
      - MarineHeatwaves.qmd
      - HabitatCompressionIndex.qmd
      - Upwelling.qmd
      - DissolvedOxygen.qmd
      - OceanAcidification.qmd
      - SnowWaterEquivalent.qmd
      - MaximumStreamTemperature.qmd
      - Streamflow.qmd
      
    - part: "Focal Components of Ecological Integrity"
      chapters:
      - Copepods.qmd
      - Krill.qmd
      - NCCForage.qmd
      - CCCForage.qmd
      - SCCForage.qmd
      - CPSSurvey.qmd
      - JuvenileSalmon.qmd
      - SalmonStoplightTables.qmd
      - ChinookSalmonEscapementColumbia.qmd
      - ChinookSalmonEcosystemCalifornia.qmd
      - GroundfishStockAbundance.qmd
      - JuvenileGroundfish.qmd
      - GroundfishPortAvailability.qmd
      - HMSRecruitmentSSB.qmd
      - HMSDiets.qmd
      - SeabirdProductivity.qmd
      - SeabirdDensity.qmd
      - SeabirdMortality.qmd
      - SeabirdDiet.qmd
      - SeaLionProductivity.qmd
      - WhaleEntanglement.qmd
      - HarmfulAlgalBlooms.qmd
      
    - part: "Fishing and Non-Fishing Human Activities"
      chapters:
      - FisheryLandings.qmd
      - FisheryRevenue.qmd
      - OtherHumanActivities.qmd
      - SpatialInteractionsOceanUse.qmd

    - part: "Human Wellbeing"
      chapters:
      - SocialVulnerability.qmd
      - FleetIncomeDiversification.qmd
      - NonFisheryIncomeDiversification.qmd
      - FisheryRevenueConcentration.qmd
      - FisheriesParticipationNetworks.qmd
      
bibliography: esr-bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 1
    number-depth: 1
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 20mm
    margin-bottom: 30mm
    filters:
    - quarto
    - section-bibliographies
    citeproc: false



